name = "MuesliMaterials"
uuid = "15d96d4e-a55c-433f-b8eb-a88007b7373b"
authors = ["Henrik Jakob <jakob@ibb.uni-stuttgart.de> and contributors"]
version = "0.1.0-dev"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
MuesliMaterialsWrapper_jll = "6dead231-e870-550e-b74b-2a3bf2cfaa53"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[weakdeps]
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[extensions]
TensorsExt = "Tensors"

[compat]
CxxWrap = "0.16.0"
MuesliMaterialsWrapper_jll = "0.12"
Tensors = "1.16.1"
Tullio = "0.3.8"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[targets]
test = ["Test", "Tensors", "Aqua"]
