name = "Muesli"
uuid = "15d96d4e-a55c-433f-b8eb-a88007b7373b"
authors = ["Henrik Jakob <jakob@ibb.uni-stuttgart.de> and contributors"]
version = "0.1.0-dev"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
MuesliMaterialsWrapper_jll = "6dead231-e870-550e-b74b-2a3bf2cfaa53"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"

[compat]
CxxWrap = "0.17.0"
julia = "1.10"
libcxxwrap_julia_jll = "0.14.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
