## File to hold docstrings for the wrapped MUESLI types and functions.
##
## The bindings themselves are generated by CxxWrap at load time, so there is nowhere to
## attach documentation in the usual way; the empty `function ... end` declarations below give
## the docstrings a home without adding methods.

# ---------------------------------------------------------------------------------------
# Tensor types
# ---------------------------------------------------------------------------------------

@doc """
    Ivector(v::AbstractVector)
    Ivector(a, b, c)

A three-component vector, MUESLI's `ivector`.

Supports 1-based indexing, iteration and `convert(Vector{Float64}, v)`.

# Examples
```julia
v = Ivector([1.0, 2.0, 3.0])
v[2]                              # 2.0
convert(Vector{Float64}, v)
```
"""
Ivector

@doc """
    Itensor(m::AbstractMatrix)
    Itensor(a::AbstractVector, b::AbstractVector, c::AbstractVector)
    Itensor(a00, a01, a02, a10, a11, a12, a20, a21, a22)

A general second-order tensor in three dimensions, MUESLI's `itensor`.

# Details
The matrix constructor takes a `3 × 3` Julia matrix. Julia stores matrices column-major while
MUESLI's constructor is row-major, so the components are reordered on the way in — the round
trip is faithful and nothing is transposed. Any other shape raises an error.

Behaves like a `3 × 3` array: indexing and slicing (both 1-based), `axes`, `length`, `ndims`,
iteration, and `convert` to `Matrix{Float64}`. With
[Tensors.jl](https://github.com/Ferrite-FEM/Tensors.jl) loaded it also converts to
`Tensor{2, 3}`.

Finite strain material points take the deformation gradient as an `Itensor`, since it is not
symmetric.

# Examples
```julia
F = Itensor([1.05 0.02 0.0; 0.0 0.98 0.01; 0.0 0.0 1.01])
F[1, 2]                           # 0.02
F[1, :]                           # first row
convert(Matrix{Float64}, F)
```

# See Also
- [`Istensor`](@ref) for the symmetric counterpart
"""
Itensor

@doc """
    Istensor(m::AbstractMatrix)
    Istensor(t00, t11, t22, t12, t20, t01)

A **symmetric** second-order tensor in three dimensions, MUESLI's `istensor`.

# Details
Only six components are stored. The matrix constructor reads the symmetric part of the `3 × 3`
matrix it is given, so a non-symmetric input is symmetrised rather than rejected.

`Istensor` is a subtype of [`Itensor`](@ref) on the C++ side, so it supports the same array
interface, and converts to `SymmetricTensor{2, 3}` when
[Tensors.jl](https://github.com/Ferrite-FEM/Tensors.jl) is loaded.

Small strain material points take the strain and return stresses as `Istensor`; in the finite
strain setting the second Piola-Kirchhoff, Kirchhoff and Cauchy stresses are `Istensor` while
the first Piola-Kirchhoff stress is a general [`Itensor`](@ref).

# Examples
```julia
ε = Istensor([0.001 0.0002 0.0; 0.0002 -0.0005 0.0001; 0.0 0.0001 0.0003])
σ = Istensor()                    # empty, to be filled by a bang method
```
"""
Istensor

@doc """
    Itensor4(a::AbstractArray{<:Real, 4})
    Itensor4()

A fourth-order tensor in three dimensions, MUESLI's `itensor4`.

# Details
The constructor takes a `3 × 3 × 3 × 3` array; anything else raises an error. The default
constructor gives an uninitialised tensor to be filled by a bang method such as
[`tangentTensor!`](@ref MuesliMaterials.tangentTensor!).

Indexing is 1-based in all four slots.

# Examples
```julia
ℂ = Itensor4()
tangentTensor!(mp, ℂ)
ℂ[1, 1, 2, 2]
```
"""
Itensor4

@doc """
    ArrayOfITensors()

A growable list of [`Itensor`](@ref) values, for MUESLI routines that take several tensors at
once.

Use `push!` to append a `3 × 3` Julia matrix, `clear!` to empty it and `size` for the count.
"""
ArrayOfITensors

@doc """
    ArrayOfIsTensors()

A growable list of [`Istensor`](@ref) values, for MUESLI routines that take several symmetric
tensors at once — the per-branch relaxation strains of a viscoelastic material, for instance.

Use `push!` to append a `3 × 3` Julia matrix, `clear!` to empty it and `size` for the count.
"""
ArrayOfIsTensors

# ---------------------------------------------------------------------------------------
# Material properties
# ---------------------------------------------------------------------------------------

@doc """
    MaterialProperties()

A map of named material parameters, MUESLI's `materialProperties`.

# Details
This is how MUESLI passes named parameters to a material constructor, and it is the only route
for models with many parameters. The backing store is a multimap, so setting the same key more
than once keeps every value — several models rely on that to receive a list.

# Examples
```julia
props = MaterialProperties()
setProperty!(props, "young", 210000.0)
setProperty!(props, "poisson", 0.3)

material = ElasticIsotropicMaterial(props)
```

# See Also
- [`setProperty!`](@ref MuesliMaterials.setProperty!), [`getProperty`](@ref MuesliMaterials.getProperty)
- [`setString!`](@ref MuesliMaterials.setString!), [`getString`](@ref MuesliMaterials.getString)
"""
MaterialProperties

@doc """
    setProperty!(props::MaterialProperties, key::String, value::Real)

Add a named numeric property.

Setting the same key more than once **keeps both values** rather than replacing the first, so
that models expecting a list of values receive one.

# See Also
- [`getProperty`](@ref MuesliMaterials.getProperty)
"""
function setProperty! end

@doc """
    getProperty(props::MaterialProperties, key::String)
    getProperty(material, name::PropertyName)

Read a property back.

From a [`MaterialProperties`](@ref MuesliMaterials.MaterialProperties) map, returns **all**
values stored under `key` as a `Vector{Float64}`; an unknown key gives an empty vector rather
than an error.

From a *material*, takes one of the `PR_*` constants — `PR_YOUNG`, `PR_POISSON`, `PR_LAMBDA`,
`PR_MU`, `PR_BULK`, `PR_YIELD` and so on — and returns that single value.

# Examples
```julia
getProperty(props, "young")                # [210000.0]
getProperty(material, PR_YOUNG)            # 210000.0
```
"""
function getProperty end

@doc """
    setString!(props::MaterialProperties, key::String, value::String)

Set a string-valued option.

# Details
MUESLI spells a flag as a bare `"key value"` entry in the property map rather than as a key
with a string value, so this concatenates the two. Read it back with
[`getString`](@ref MuesliMaterials.getString) and test for it with
[`hasKeyword`](@ref MuesliMaterials.hasKeyword).
"""
function setString! end

@doc """
    getString(props::MaterialProperties, key::String)

Read a string-valued option.

Returns `"NotFound"` if the key was never set — it does not raise.
"""
function getString end

@doc """
    hasKeyword(props::MaterialProperties, key::String)

Whether a string-valued option was set under `key`.
"""
function hasKeyword end

# ---------------------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------------------

@doc """
    check(material)

Ask MUESLI whether the material's parameters are admissible.

Worth calling once after construction: an inadmissible parameter set is otherwise only noticed
much later, when a stress evaluation returns nonsense.

# Returns
`true` if the material is consistent.
"""
function check end

@doc """
    print(material)

Print MUESLI's own description of the material — its type and derived constants — to `stdout`.
"""
function print end

@doc """
    createMaterialPoint(material)

Create a material point for `material`.

Equivalent to calling the matching `...MP` constructor, e.g. `ElasticIsotropicMP(material)`.

# See Also
- [`updateCurrentState`](@ref MuesliMaterials.updateCurrentState)
"""
function createMaterialPoint end

@doc """
    ElasticIsotropicMaterial(E::Real, ν::Real, ρ::Real = 1.0)
    ElasticIsotropicMaterial(props::MaterialProperties)

Linear isotropic elasticity, MUESLI's `elasticIsotropicMaterial`.

# Arguments
- `E`: Young's modulus
- `ν`: Poisson's ratio
- `ρ`: density (default: `1.0`)
- `props`: alternatively a property map carrying `"young"` and `"poisson"`

# Details
The response is ``\\sigma = 2\\mu\\varepsilon + \\lambda\\,\\mathrm{tr}(\\varepsilon)\\,I``,
with the Lamé parameters derived from `E` and `ν`.

# Examples
```julia
material = ElasticIsotropicMaterial(210000.0, 0.3)
mp = ElasticIsotropicMP(material)
```

# See Also
- [`ElasticIsotropicMP`](@ref)
"""
ElasticIsotropicMaterial

@doc """
    ElasticAnisotropicMaterial(c::AbstractVector, ρ::Real = 1.0)
    ElasticAnisotropicMaterial(props::MaterialProperties)

Fully anisotropic linear elasticity.

`c` must hold the **21** independent constants of the elasticity tensor; any other length
raises an error.
"""
ElasticAnisotropicMaterial

@doc """
    ElasticOrthotropicMaterial(c::AbstractVector, ρ::Real = 1.0)
    ElasticOrthotropicMaterial(props::MaterialProperties)

Orthotropic linear elasticity.

`c` must hold **9** constants; any other length raises an error.
"""
ElasticOrthotropicMaterial

@doc """
    ElasticTransverselyisotropicMaterial(c::AbstractVector, ρ::Real = 1.0)
    ElasticTransverselyisotropicMaterial(props::MaterialProperties)

Transversely isotropic linear elasticity.

`c` must hold **6** constants; any other length raises an error.
"""
ElasticTransverselyisotropicMaterial

@doc """
    SplasticMaterial(E, ν, ρ, Hiso, Hkine, yield, xalpha, plasticityType::String)
    SplasticMaterial(props::MaterialProperties)

Small strain plasticity with isotropic and kinematic hardening.

# Arguments
- `Hiso`, `Hkine`: isotropic and kinematic hardening moduli
- `yield`: initial yield stress
- `plasticityType`: the hardening law, as a MUESLI keyword
"""
SplasticMaterial

@doc """
    ViscoelasticMaterial(E, ν, ρ, nvisco::Integer, eta::AbstractVector, tau::AbstractVector)
    ViscoelasticMaterial(props::MaterialProperties)

Small strain viscoelasticity with `nvisco` Maxwell branches.

`eta` and `tau` give the viscosity and relaxation time of each branch.
"""
ViscoelasticMaterial

@doc """
    ViscoplasticMaterial(E, ν, ρ, Hiso, Hkine, yield, plasticityType::String, eta, alpha)
    ViscoplasticMaterial(props::MaterialProperties)

Small strain viscoplasticity, with `eta` and `alpha` setting the rate dependence.
"""
ViscoplasticMaterial

@doc """
    GTN_Material(E, ν, ρ, q1, q2, yield)

Gurson-Tvergaard-Needleman ductile damage.
"""
GTN_Material

@doc """
    Gurson_Material(E, ν, ρ, xRinf, xRb, yield)

Gurson porous plasticity.
"""
Gurson_Material

@doc """
    Lemaitre_Material(E, ν, ρ, r, s, yield, xR_inf, xR_b)

Lemaitre ductile damage.
"""
Lemaitre_Material

@doc """
    LemKin_Material(E, ν, ρ, r, s, yield, xR_inf, xR_b, xa, xb)

Lemaitre damage with kinematic hardening.
"""
LemKin_Material

@doc """
    NeoHookeMaterial(props::MaterialProperties)

Compressible neo-Hookean hyperelasticity, MUESLI's `neohookeanMaterial`.

Build it from a property map carrying `"young"` and `"poisson"`. At ``F = I`` the material is
stress free and stores no energy.

# Examples
```julia
props = MaterialProperties()
setProperty!(props, "young", 210000.0)
setProperty!(props, "poisson", 0.3)

material = NeoHookeMaterial(props)
mp = NeoHookeMP(material)
```

# See Also
- [`NeoHookeMP`](@ref)
"""
NeoHookeMaterial

@doc """
    SVKMaterial(props::MaterialProperties)

Saint Venant-Kirchhoff hyperelasticity — the linear relation between the Green-Lagrange strain
and the second Piola-Kirchhoff stress.
"""
SVKMaterial

@doc """
    YeohMaterial(props::MaterialProperties)

Yeoh hyperelasticity, an invariant-based rubber model.
"""
YeohMaterial

@doc """
    MooneyMaterial(props::MaterialProperties)

Mooney-Rivlin hyperelasticity.
"""
MooneyMaterial

@doc """
    ArrudaBoyceMaterial(props::MaterialProperties)

Arruda-Boyce eight-chain hyperelasticity.
"""
ArrudaBoyceMaterial

@doc """
    FplasticMaterial(props::MaterialProperties)

Finite strain plasticity.
"""
FplasticMaterial

# ---------------------------------------------------------------------------------------
# Material points
# ---------------------------------------------------------------------------------------

@doc """
    ElasticIsotropicMP(material::ElasticIsotropicMaterial)

The material point of a linear isotropic elastic material.

Carries the state at one location. Push a strain into it with
[`updateCurrentState`](@ref MuesliMaterials.updateCurrentState), then read stresses, tangents
and energies out of it.
"""
ElasticIsotropicMP

@doc """
    NeoHookeMP(material::NeoHookeMaterial)

The material point of a neo-Hookean material. Takes the deformation gradient rather than a
strain tensor.
"""
NeoHookeMP

@doc """
    SVKMP(material::SVKMaterial)

The material point of a Saint Venant-Kirchhoff material.
"""
SVKMP

@doc """
    YeohMP(material::YeohMaterial)

The material point of a Yeoh material.
"""
YeohMP

@doc """
    updateCurrentState(mp, t::Real, strain::Istensor)
    updateCurrentState(mp, t::Real, F::Itensor)

Set the trial state of the material point at time `t`.

# Details
Small strain points take the linearised strain as an [`Istensor`](@ref); finite strain points
take the deformation gradient as a general [`Itensor`](@ref).

This sets the *current* state only. A solver iterating on a step calls this repeatedly, then
either accepts the step with
[`commitCurrentState`](@ref MuesliMaterials.commitCurrentState) or discards it with
[`resetCurrentState`](@ref MuesliMaterials.resetCurrentState).

There is no bang, because the call advances the point's own history rather than filling an
argument.
"""
function updateCurrentState end

@doc """
    commitCurrentState(mp)

Accept the current state as converged.

# See Also
- [`resetCurrentState`](@ref MuesliMaterials.resetCurrentState)
"""
function commitCurrentState end

@doc """
    resetCurrentState(mp)

Discard the current state and return to the last converged one.
"""
function resetCurrentState end

@doc """
    setConvergedState(mp, t::Real, strain)

Set the converged state directly, bypassing the trial state.

Useful when restoring a material point from stored history. Plastic, viscoelastic and
viscoplastic points take additional internal variables; see their MUESLI documentation.
"""
function setConvergedState end

@doc """
    stress!(mp, σ::Istensor)

Compute the Cauchy stress of a small strain material point into `σ`.

# Examples
```julia
σ = Istensor()
stress!(mp, σ)
```
"""
function stress! end

@doc """
    deviatoricStress!(mp, s::Istensor)

Compute the deviatoric part of the stress into `s`.
"""
function deviatoricStress! end

@doc """
    pressure(mp)

The pressure, i.e. minus one third of the trace of the stress.
"""
function pressure end

@doc """
    tangentTensor!(mp, ℂ::Itensor4)

Compute the small strain tangent ``\\partial\\sigma/\\partial\\varepsilon`` into `ℂ`.

For a linear isotropic material this is
``\\mathbb{C}_{ijkl} = \\lambda\\delta_{ij}\\delta_{kl} +
\\mu(\\delta_{ik}\\delta_{jl} + \\delta_{il}\\delta_{jk})``, and contracting it with the strain
reproduces the stress.
"""
function tangentTensor! end

@doc """
    firstPiolaKirchhoffStress!(mp, P::Itensor)

Compute the first Piola-Kirchhoff stress ``P`` into `P`.

``P`` is **not** symmetric, hence the general [`Itensor`](@ref). It relates to the second
Piola-Kirchhoff stress by ``P = FS``.
"""
function firstPiolaKirchhoffStress! end

@doc """
    secondPiolaKirchhoffStress!(mp, S::Istensor)

Compute the symmetric second Piola-Kirchhoff stress ``S`` into `S`.

``S`` is unaffected by a rigid rotation of the deformation, which makes it the convenient
measure for a material-frame formulation.
"""
function secondPiolaKirchhoffStress! end

@doc """
    KirchhoffStress!(mp, τ::Istensor)

Compute the Kirchhoff stress ``\\tau = J\\sigma = PF^{T}`` into `τ`.
"""
function KirchhoffStress! end

@doc """
    CauchyStress!(mp, σ::Istensor)

Compute the Cauchy (true) stress ``\\sigma`` into `σ`.
"""
function CauchyStress! end

@doc """
    firstPiolaKirchhoffStressNumerical!(mp, P::Itensor)

Compute the first Piola-Kirchhoff stress by numerically differentiating the stored energy.

Slower and less accurate than
[`firstPiolaKirchhoffStress!`](@ref MuesliMaterials.firstPiolaKirchhoffStress!), and meant for
checking: if the analytic and numerical stresses disagree, the model is wired up wrongly.
"""
function firstPiolaKirchhoffStressNumerical! end

@doc """
    secondPiolaKirchhoffStressNumerical!(mp, S::Istensor)

Compute the second Piola-Kirchhoff stress by numerical differentiation of the stored energy.

!!! warning "Broken upstream"
    This does not currently produce a usable result. MUESLI's
    `finiteStrainMP::secondPiolaKirchhoffStressNumerical` assigns a general `itensor` into the
    symmetric `istensor` output, which never reaches the symmetric tensor's storage, so `S`
    keeps whatever was already in memory. It is intermittent — sometimes the memory happens to
    look plausible — which makes it worse than a hard failure.

    Use [`firstPiolaKirchhoffStressNumerical!`](@ref MuesliMaterials.firstPiolaKirchhoffStressNumerical!),
    which is correct, and convert with ``S = F^{-1}P`` if you need the second measure.
"""
function secondPiolaKirchhoffStressNumerical! end

@doc """
    deformationGradient(mp)

The current deformation gradient, as an [`Itensor`](@ref).
"""
function deformationGradient end

@doc """
    convergedDeformationGradient(mp)

The deformation gradient of the last converged state.
"""
function convergedDeformationGradient end

@doc """
    convectedTangent!(mp, c::Itensor4)

Compute the convected (material) tangent into `c`.
"""
function convectedTangent! end

@doc """
    materialTangent!(mp, c::Itensor4)

Compute the material tangent into `c`.
"""
function materialTangent! end

@doc """
    spatialTangent!(mp, c::Itensor4)

Compute the spatial tangent into `c`.
"""
function spatialTangent! end

@doc """
    storedEnergy(mp)

The stored (elastic) energy density of the current state.

For linear elasticity this is ``\\tfrac{1}{2}\\sigma:\\varepsilon``, and for a hyperelastic
material it vanishes at ``F = I``.
"""
function storedEnergy end

@doc """
    effectiveStoredEnergy(mp)

The stored energy corrected for damage, where the model defines one.
"""
function effectiveStoredEnergy end

@doc """
    deviatoricEnergy(mp)

The deviatoric (isochoric) part of the stored energy.
"""
function deviatoricEnergy end

@doc """
    volumetricEnergy(mp)

The volumetric part of the stored energy.
"""
function volumetricEnergy end

@doc """
    kineticPotential(mp)

The kinetic potential of the current state.
"""
function kineticPotential end

@doc """
    energyDissipationInStep(mp)

The energy dissipated between the converged and the current state — zero for a purely elastic
material.
"""
function energyDissipationInStep end

@doc """
    getCurrentState(mp)

The current state of the material point, as a
[`InterfaceState`](@ref MuesliMaterials.InterfaceState).
"""
function getCurrentState end

@doc """
    getConvergedState(mp)

The last converged state of the material point.
"""
function getConvergedState end

@doc """
    InterfaceState

A snapshot of a material point: a time, a scalar, and lists of vectors, symmetric tensors and
general tensors whose meaning depends on the model.

Read it with [`getTime`](@ref MuesliMaterials.getTime),
[`getStensor`](@ref MuesliMaterials.getStensor) and friends. All the list accessors are
**1-based** and range-checked.
"""
InterfaceState

@doc """
    getTime(state::InterfaceState)

The time stamp of the state.
"""
function getTime end

@doc """
    getStensorSize(state::InterfaceState)

How many symmetric tensors the state holds.
"""
function getStensorSize end

@doc """
    getStensor(state::InterfaceState, i::Integer)

The `i`-th symmetric tensor of the state, **1-based**. Out-of-range indices raise.
"""
function getStensor end

@doc """
    getTensorSize(state::InterfaceState)

How many general tensors the state holds.
"""
function getTensorSize end

@doc """
    getTensor(state::InterfaceState, i::Integer)

The `i`-th general tensor of the state, **1-based**. Out-of-range indices raise.
"""
function getTensor end

@doc """
    getVectorSize(state::InterfaceState)

How many vectors the state holds.
"""
function getVectorSize end

@doc """
    getVector(state::InterfaceState, i::Integer)

The `i`-th vector of the state, **1-based**. Out-of-range indices raise.
"""
function getVector end

@doc """
    plasticSlip(mp)

The accumulated plastic slip.
"""
function plasticSlip end

@doc """
    getCurrentPlasticStrain(mp)

The plastic strain of the current state, as an [`Istensor`](@ref).
"""
function getCurrentPlasticStrain end

@doc """
    getConvergedPlasticStrain(mp)

The plastic strain of the last converged state.
"""
function getConvergedPlasticStrain end

@doc """
    getDamage(mp)

The damage variable of the current state.
"""
function getDamage end

@doc """
    isFullyDamaged(mp)

Whether the material point has reached full damage.
"""
function isFullyDamaged end
